### ISSUE TITLE
AssertionError: Not Enough Backgrounds (0) for 100 

### ISSUE THREAD

**Issue by red010182** [hector-sab/DIM_DataCreation#2]
I've downloaded SURREAL dataset (~85GB) and put it in `./data`
main.py
```
from DataCreation2 import DataCreation

# Folder where the surreal data is located
SUR_DATA_DIR = './data/cmu/train/run0/01_01'

# Output Directory, empty folder
OUT_DIR = './data/Deep-Image-Matting/data/'

# Backgrounds, empty folder
BG_DIR = './data/Deep-Image-Matting/backgrounds/'

create = DataCreation(ipath=SUR_DATA_DIR, opath=OUT_DIR, bg_path=BG_DIR)
create.create_data()

```

```
python main.py 
Processing 01_01_c0001
./data/cmu/train/run0/01_01/01_01_c0001.mp4
./data/cmu/train/run0/01_01/01_01_c0001_segm.mat
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    create.create_data()
  File "/work/DIM_DataCreation/DataCreation2.py", line 110, in create_data
    create.create_data()
  File "/work/DIM_DataCreation/PaddingBackgroundCreation.py", line 44, in create_data
    assert num_bg_fls>=self.num_bgs, "Not Enough Backgrounds (%d) for %d "%(num_bg_fls,self.num_bgs)
AssertionError: Not Enough Backgrounds (0) for 100 
```

**Comment by hector-sab** [comment]
Backgrounds folder should be not empty, it should contain the images you want to use has backgrounds.
